CUDA_VISIBLE_DEVICES=[2,3,4] python ../inference_magic.py\
    --language_model_code_path ../language_model/\
    --language_model_name gpt2\
    --clap_path ../clip/\
    --clap_model_name ../clip/CLAP/assets/checkpoints/no_fusion_no_keyword_to_caption.pt\
    --test_image_prefix_path ../softlinks/AudioCaps_data/\
    --test_path ../data/AudioCaps/AudioCaps_test.json\
    --decoding_len 30\
    --sample_rate 48000\
    --k 45\
    --alpha 0.1\
    --beta 2.0\
    --save_name exp.json\
    --dataset audiocaps\
    --include_prompt_magic False