CUDA_VISIBLE_DEVICES="1" python ../inference_magic.py\
    --language_model_code_path ../language_model/\
    --language_model_name facebook/opt-1.3b\
    --audio_code_path ../clip/\
    --audio_pt_file ../clip/WavCaps/retrieval/assets/HTSAT-BERT-FT-AudioCaps.pt\
    --inference_file_prefix ../softlinks/AudioCaps_data/\
    --GT_captions_path ../data/AudioCaps/AudioCaps_val.json\
    --decoding_len 78\
    --sample_rate 32000\
    --k 45\
    --save_name ext_keywords\
    --dataset audiocaps\
    --include_prompt_magic False\
    --experiment hyperparam_experiments\
    --path_to_AudioSet_keywords ../data/AudioSet/class_labels_indices.csv\
    --path_to_ChatGPT_keywords ../data/sounding_objects/chatgpt_audio_tags.csv