CUDA_VISIBLE_DEVICES=[5,6,7] python ../inference_magic.py\
    --language_model_code_path ../language_model/\
    --language_model_name gpt2\
    --clip_path ../clip/AudioCLIP/\
    --clip_name /shared-network/sfauth/data/MAGIC/image_captioning/clip/AudioCLIP/assets/AudioCLIP-Full-Training.pt\
    --test_image_prefix_path ../data/clotho_v2.1/test_sounds/\
    --test_path ../data/clotho_v2.1/clotho_v2.1_test.json\
    --decoding_len 16\
    --sample_rate 44100\
    --k 250\
    --alpha 5.1\
    --beta 20.0\
    --save_path_prefix ../inference_result/clotho_v2.1/magic\
    --save_name magic_clotho_v2.1_gpt2_run_an_audio_clip_of_a_result_k_250.json