CUDA_VISIBLE_DEVICES=[5,6,7] python ../inference_magic.py\
    --language_model_code_path ../language_model/\
    --language_model_name gpt2\
    --clip_path ../softlinks/audio_clip_repo/\
    --clip_name ../softlinks/audioclip_partial_pt\
    --test_image_prefix_path ../softlinks/audio_clip_test_data/\
    --test_path ../softlinks/test_json\
    --decoding_len 25\
    --sample_rate 44100\
    --k 8\
    --alpha 0.1\
    --beta 2.0\
    --save_path_prefix ../inference_result/clotho_v2.1/magic\
    --save_name magic_clotho_v2.1_demo_gt_partial_aclip_alpha_0.1_beta_2_mean_logits.json
